server:
  port: ${PORT:8765}


info:
  component: SV Edge Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    example:
      path: '/example/**'
      serviceId: example


ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false



logging:
    level:
        ROOT: INFO
        org.springframework.web: DEBUG
        com.netflix.discovery: debug

