version: "3.5"
services:
  serverapi:
    build:
      context: ../
      dockerfile: ./docker/server/spring-boot-edge-server.Dockerfile
      args:
        - POM_VERSION=${POM_VERSION}
        - ARTIFACT_ID=${ARTIFACT_ID}
        - version=${version}
    image: "softvisionlvcp/spring-boot-edge-server:latest"
    ports:
      - "8761:8761"
    networks:
      - proxynet

networks:
  proxynet:
    name: custom_network